### ISSUE TITLE
Stuck on Waiting for Socket Connection

### ISSUE THREAD

**Issue by Varean** [advplyr/fotosho#3]
After installing the docker image on Unraid, I was able to log into the WebUI and start a scan. After the scan was complete I refreshed the page and noticed that it was still working on generating Thumbnails and not showing me the pictures. I let it complete and after several hours it finished generating the Thumbnails according to the log, but now I can't view the WebUI in a browser (i've tried Chrome/Firefox and even my phone) it just states 'Waiting for socket connection..."

**Comment by advplyr** [comment]
Can you check in your thumbnails directory to see if the thumbnails were generated.

Also, update to the latest version. I pushed a fix yesterday afternoon. Running the initial scan again should be faster the second time around if you use the same directories.

If the socket connection is still not getting established, then copy paste the last 20 lines of the log file.

**Comment by Varean** [comment]
I checked and the Thumbnails are there, I see the .webp files in the directory.

I updated the image 

I can't get to the screen to even do a scan, when I visit the WebUI it just tells me 'Waiting for Socket Connection'

The logs from Unraid is

ENV production
Config /config /photos /thumbnails
=== Starting Server ===
Running on http://0.0.0.0:80
Got auth root
Socket Connected QInP_RnJyYYGj7LcAAAB
Socket Connected mbOfuD1zhskb_fhJAAAD

**Comment by advplyr** [comment]
Did you use the default port mapping 13377?

I just pushed another update with additional logging around the socket connection. If you could force that update again that will give us more insight.

**Comment by Varean** [comment]
I did adjust the default port # as a troubleshooting method, but I set it back after that didn't resolve the issue

=== Starting Server ===
Running on http://0.0.0.0:80
Got auth root
[SOCKET] Socket Connected 2oUT2lSSUmcQZ9sZAAAB
Emit initial payload to socket: {"albums":[{"id":"starred","name":"Starred","photos":[],"created_at":1626591471137,"created_by":"system"}],"settings":{"order_by":"added_at","order_desc":true,"card_size":"md","auto_slide":false,"slide_duration":8000},"scanning":false,"num_photos":49787,"isInitialized":false,"photoPath":"/photos","thumbnailPath":"/thumbnails","configPath":"/config","user":{"username":"root","type":"root"}}
[SOCKET] Socket disconnect from client "root" 2oUT2lSSUmcQZ9sZAAAB
[SOCKET] Socket Connected IlwG9imUKctHzKQXAAAD

**Comment by advplyr** [comment]
Alright.. I appreciate you helping me troubleshoot this.

What OS are you using to view the web GUI?

I pushed an update that skips the initial socket long-polling as explained [here](https://stackoverflow.com/a/38559152/7431543).
And logging for the web client to see if the socket shows any connection errors in the dev tools.

**Comment by Varean** [comment]
I am using Windows 10, and I have tried this in both Chrome and Firefox

Google Chrome version is
Version 91.0.4472.164 (Official Build) (64-bit)

Firefox is Version 90.0 (64-bit)

**Comment by advplyr** [comment]
Looks like it was the long polling. The scan should be showing percentage values as it progresses.

**Comment by Varean** [comment]
So, the scan was completed successfully and I am able to load the collection/thumbnails correctly and search.

Two things as questions, one possibly related to these changes and one not

When I load the page, it takes me to the launch page and wants me to run another scan, is there a way to get past that screen without running another scan?

And I checked the log and keep seeing this repeat over and over in the logs

Emit initial payload to socket: {"albums":[{"id":"starred","name":"Starred","photos":[],"created_at":1626591471137,"created_by":"system"}],"settings":{"order_by":"added_at","order_desc":true,"card_size":"md","auto_slide":false,"slide_duration":8000},"scanning":false,"num_photos":49787,"isInitialized":true,"photoPath":"/photos","thumbnailPath":"/thumbnails","configPath":"/config","user":{"username":"root","type":"root"}}
[SOCKET] Socket disconnect from client "root" after 39564ms @1626715788586d0MSuk93n-zYDp3YAAAD
[SOCKET] Socket disconnect from client "root" after 39564ms @1626715788586d0MSuk93n-zYDp3YAAAD
e":"No such container: 73c845d59792"}
e":"No such container: 73c845d59792"}
e":"No such container: 73c845d59792"}
e":"No such container: 73c845d59792"}
e":"No such container: 73c845d59792"}
e":"No such container: 73c845d59792"}
e":"No such container: 73c845d59792"}
e":"No such container: 73c845d59792"}
e":"No such container: 73c845d59792"}
e":"No such container: 73c845d59792"}
e":"No such container: 73c845d59792"}
e":"No such container: 73c845d59792"}
e":"No such container: 73c845d59792"}
e":"No such container: 73c845d59792"}

**Comment by advplyr** [comment]
The scan page should only show the first time the docker container gets started, no matter where you are accessing the GUI from. If you restart the docker container it will need to scan again so that the photo directory stays in sync.

In your log you you pasted the "isInitialized" flag is what determines whether you will see the scan page. If not initialized then show scan page.

The "No such container" error might be because Unraid didn't remove the old docker image when updating. You can open the terminal and run `docker image prune -a` to remove any orphan docker images. You should also be able to see orphans in the list of docker containers, and remove them via the gui.

**Comment by Varean** [comment]
Awesome, 

Everything seems to be working, I appreciate your hard work, thank you very much.
